config/routes.rb
Rails.application.routes.draw do
  root 'splash#home'
  get '/lineup', to: 'splash#lineup', as: 'lineup'
  get '/tickets', to: 'splash#tickets', as: 'tickets'
  get '/directions', to: 'splash#directions', as: 'directions'
  get '/gallery', to: 'splash#gallery', as: 'gallery'
  get '/press', to: 'splash#press', as: 'press'
  get '/contact', to: 'splash#contact', as: 'contact'
  get '/lodging', to: 'splash#lodging', as: 'lodging'
  get '/artist-bios', to: 'splash#bios', as: 'bios'
  get '/shuttle', to: 'splash#shuttle', as: 'shuttle'
  get '/faq', to: 'splash#faq', as: 'faq'
  get '/terms', to: 'splash#terms', as: 'terms'
  get '/map', to: 'splash#map', as: 'map'
  get '/past-lineup', to: 'splash#past-lineup', as: 'past-lineup'
  get '/suscribe', to: 'splash#suscribe', as: 'suscribe'
  get '/send_contact', to: 'splash#send_contact', as: 'send_contact'
  get '/rail-jam', to: 'splash#rail-jam', as: 'rail-jam'
    
  post '/load_more_gallery', to: 'splash#load_more_gallery'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
# class Contact < MailForm::Base
#   attribute :name,      :validate => true
#   attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
#   attribute :message
#   attribute :nickname,  :captcha  => true

#   # Declare the e-mail headers. It accepts anything the mail method
#   # in ActionMailer accepts.
#   def headers
#     {
#       :subject => "My Contact Form",
#       :to => "webmaster@neco.com",
#       :from => %("#{name}" <#{email}>)
#     }
#   end
# end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def home
      #open_weather_api = OpenWeatherAPI::API.new api_key: "62bfa8521c1ad8c8e4c86669209ee8d0", default_language: 'en', default_units: 'imperial', default_country_code: 'us'
      
      #@json = open_weather_api.current city: 'New York', country_code: 'us'
      
      #render json: @json["weather"][0]["icon"]
      return
  end

  def lineup
  end

  def tickets
  end

  def lodging
  end

  def directions
  end

  def gallery
  end
    
  def load_more_gallery
    _data = params[:data]
    _qt = _data[:numitems].to_i
    _iniVal = 440 + _qt
    _qtAdd = 49
    _endVal = _iniVal + _qtAdd
    _show_loadmore = true
      
    if _endVal > 1059
        _endVal = 1059
        _show_loadmore = false
    end
    
    _html = ""
    for i in _iniVal.._endVal
       _html = _html + "<img alt='' src='https://s3.amazonaws.com/minuszero2/thumbs1/#{i}.jpg' data-image='https://s3.amazonaws.com/minuszero2/#{i}.jpg' data-description='MINUS ZERO 2017'>"
    end
      
    render json: { :html_items => _html, :show_loadmore => _show_loadmore, :success => true }
    return
  end

  def bios
  end
    
  def press
    #@list_id = "7782aba153"
    #@data = Gibbon::Request.lists(@list_id).members.retrieve()
    #render json: @data
  end
    
  def suscribe
    @list_id = "7782aba153"
    begin
        #require 'Gibbon'
        @data = Gibbon::Request.lists(@list_id).members.create(body: {email_address: "#{params[:email]}", status: "subscribed"})
    rescue
        @data = {:error => "Sorry. We ran into an error with your subscription."}
    end
    
    render json: @data
    return
  end
    
  def send_contact
    @email = params[:email]
    @message = params[:message]
    @subject = params[:subject]
    
    ApplicationMailer.contact_email(@email, @subject, @message).deliver 
    
    render json: @data
    return
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def parsed_tweet b
    _parsed_tweet = b.text.dup

    b.urls.each do |entity|
      html_link = link_to(entity.display_url.to_s, entity.expanded_url.to_s, target: '_blank')
      _parsed_tweet.sub!(entity.url.to_s, html_link)
    end

    b.media.each do |entity|
      html_link = link_to(entity.display_url.to_s, entity.expanded_url.to_s, target: '_blank')
      _parsed_tweet.sub!(entity.url.to_s, html_link)
    end


    _parsed_tweet.html_safe
  end
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/views/layouts/_footer.html.erb
<footer id="footer">
  <div class="container-fluid">
    <ul class="list-unstyle list-inline text-center">
      <!-- <li><a href="">PARTNERS</a></li> -->
      <li class="top-bottom"><%= image_tag('kathy-ireland-logo.png') %></li>
      <li class="top-bottom"><%= image_tag('encore-endevor-one.png') %></li>
    </ul>
    <ul class="list-unstyle list-inline text-center">
      <!-- <li><a href="">PARTNERS</a></li> -->
      <!-- <li class="top-bottom"><%= image_tag('kathy-ireland-logo.png') %></li>
      <li class="top-bottom"><%= image_tag('encore-endevor-one.png') %></li> -->
      <li class="top-bottom"><%= link_to "CONTACT", contact_path %></li>
      <li class="top-bottom"><%= link_to "TERMS", terms_path %></li>
      <!-- <li><a href=""><%= link_to "FAQ", faq_path %></a></li> -->
      <li class="top-bottom"><small>&copy; WINTER MUSIC FESTIVALS LLC</small></li>
      <!-- <li class="top-bottom"><%#= image_tag('mz-logo-white.png') %></li> -->
    </ul>
    <!-- <div class="row">
      <div class="col-xs-12 col-md-4">
        <h6>LINKS</h6>
        <ul class="list-unstyled">
          <li><a href="#">Home</a></li>
          <li><a href="#">Line Up</a></li>
          <li><a href="#">Lodging</a></li>
          <li><a href="#">Directions</a></li>
          <li><a href="#">Terms &amp; Conditions</a></li>
        </ul>
      </div>
      <div class="col-xs-12 col-md-4">
        <h6>CONTACT</h6>  
        <ul class="list-unstyled">
          <li><a href="mailto:example@tutorialspark.com">info@minuszero.com </a></li>
          <li><a href="mailto:example@tutorialspark.com">sales@minuszero.com </a></li>
        </ul>
      </div>
      <div class="col-xs-12 col-md-4">
        <h6>KEEP IN TOUCH</h6>
          <ul class="list-inline list-unstyled social-icons">
            <li><a href=""><i class="fa fa-twitter-square" aria-hidden="true"></i></a></li>
            <li><a href=""><i class="fa fa-facebook-square" aria-hidden="true"></i></a></li>
            <li><a href=""><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
            <li><a href=""><i class="fa fa-youtube-square" aria-hidden="true"></i></a></li>
          </ul>
      </div> -->
    </div>
  </div>
</footer>

app/views/layouts/_navbar-bottom.html.erb
<nav class="bottom-nav">
  
  <div class="container-fluid">
  <div class="mountain-range"></div>
    <div class="row">
      <div class="col-xs-12 col-md-12 count-down">
        <h3 class=" title text-center">Minus Zero is Coming...</h3>
        <p id="demo" class="text-center"></p>
      </div>
    </div>
    
  </div>
</nav>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
     <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="" href="#"></a>
      <%= link_to "Winter Music Festival", "/", :class => "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">
        <li><%= link_to "MERCH", "http://merch.minuszerofestival.com/", :target => "_blank", :class => "pink" %></li>
        <!-- <li><%#= link_to "TICKETS", tickets_path %></li> -->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">LINEUP<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "2017 LINEUP", lineup_path %></li>
            <li><%= link_to "2016 LINEUP", past_lineup_path %></li>
          </ul>
        </li>
        <!-- <li><%#= link_to "LODGING", lodging_path %></li> -->
       <!--  <li><%#= link_to "DIRECTIONS", directions_path %></li> -->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">INFO <span class="caret"></span></a>
          <ul class="dropdown-menu">
           <!--  <li><%= link_to "PRESS", press_path %></li> -->
            <li><%= link_to "DIRECTIONS", "https://www.stratton.com/plan-your-trip/getting-here/directions-to-stratton-mountain", :target => "_blank" %></li>
            <li><%= link_to "MAP", map_path %></li>
            <!-- <li><%#= link_to "SHUTTLE", shuttle_path %></li> -->
           <!-- <li><%#= link_to "NEED TO KNOW", faq_path %></li> -->
            <li><%= link_to "LODGING", lodging_path %></li>
            <li><%= link_to "CONTACT", contact_path %></li>
          </ul>
        </li>
         <li><%= link_to "GALLERY", gallery_path %></li>
        <!-- <li><%#= link_to "RAIL JAM", rail_jam_path %></li> -->
        
      </ul>
      <form id="emailForm" class="navbar-form navbar-right">
          <div class="form-group">
            <input type="text" class="form-control" id="email" placeholder="Sign up for email..">
          </div>
          <button onclick="createEmail()" type="submit" class="btn btn-default">JOIN</button>
        </form>
       <ul class="list-inline list-unstyled social-icons navbar-right">
          <li><%= link_to "",  "https://www.facebook.com/minuszerofest/", :class => "fa fa-facebook-square", :target => "_blank" %></a></li>
          <li><%= link_to "", "https://twitter.com/minuszerofest", :class => "fa fa-twitter-square", :target => "_blank" %></a></li>
          <li><%= link_to "",  "https://www.instagram.com/minuszerofest/", :class => "fa fa-instagram", :target => "_blank" %></a></li>
          <li><%= link_to "",  "https://www.youtube.com/watch?v=A3Ur0YZzslw&feature=youtu.be", :class => "fa fa-youtube-square", :target => "_blank" %></a></li>
        </ul>
      </div>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 7]><html lang="en-US" class="no-js lt-ie9 lt-ie8 lt-ie7"><![endif]-->
    <!--[if (IE 7)&!(IEMobile)]><html lang="en-US" class="no-js lt-ie9 lt-ie8"><![endif]-->
    <!--[if (IE 8)&!(IEMobile)]><html lang="en-US" class="no-js lt-ie9"><![endif]-->
    <!--[if gt IE 8]><!-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MinusZero</title>
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', "https://fonts.googleapis.com/css?family=Nunito:400,700,900", "https://fonts.googleapis.com/css?family=Montserrat:400,700",  media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= render 'layouts/shim' %>
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/favicon.ico" type="image/x-icon">
  </head>

  <body data-no-turbolink="true">
    <%= render 'layouts/navbar' %>
    <%= yield %>
    <%= render 'layouts/navbar-bottom' %>
    <%= render 'layouts/footer' %>
    <!-- Facebook Pixel Code -->
    <!-- Facebook Pixel Code -->
    <script>
    !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
    n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
    n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
    t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
    document,'script','https://connect.facebook.net/en_US/fbevents.js');
    fbq('init', '934571410010480'); // Insert your pixel ID here. 
    fbq('track', 'PageView');
    </script>
    <noscript><img height="1" width="1" style="display:none"
    src="https://www.facebook.com/tr?id=934571410010480&ev=PageView&noscript=1"
    /></noscript>
    <!-- DO NOT MODIFY -->
    <!-- End Facebook Pixel Code -->
    <script>
    !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
    n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
    n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
    t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
    document,'script','https://connect.facebook.net/en_US/fbevents.js');
    fbq('init', '583570585072830'); // Insert your pixel ID here.
    fbq('track', 'PageView');
    fbq('track', 'ViewContent');
    </script>
    <noscript><img height="1" width="1" style="display:none"
    src="https://www.facebook.com/tr?id=583570585072830&ev=PageView&noscript=1"
    /></noscript>
    <!-- DO NOT MODIFY -->
    <!-- End Facebook Pixel Code -->
    <script> 
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){ (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o), m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m) })(window,document,'script','https://www.google-analytics.com/analytics.js','ga'); ga('create', 'UA-87961249-1', 'auto'); ga('send', 'pageview');
    </script>
  </body>
</html>

app/views/splash/bios.html.erb
<div class="container">
	
</div>

app/views/splash/contact.html.erb
<div class="container">
	<h1 class="page-title text-center">Contact Us</h1>
	<div class="contact-form col-xs-12 col-md-6 col-md-offset-3">
		<form id="contactForm">
		  <div class="form-group">
		    <label for="contactEmail">Email address</label>
		    <input type="email" class="form-control" id="contactEmail" placeholder="Email">
		  </div>
		  <div class="form-group">
		  	<label for="contactSubject">Subject</label>
		    <select class="form-control" id="contactSubject">
		    	<option>Select Subject</option>
			  	<option>Inquiries regarding purchased tickets and wristbands</option>
			  	<option>General information and questions about Minus Zero</option>
			  	<option>Sponsorship Inquiries</option>
			  	<option>Press/Media Pass Inquiries</option>
			</select>
		  </div>
		  <div class="form-group">
		  	<label for="contactMessage">Body</label>
		    <textarea class="form-control" rows="3" id="contactMessage"></textarea>
		  </div>
          <div class="form-group">
            <label for="captcha" id="captcha_label"></label>
            <input type="captcha" class="form-control" id="captchaObject" placeholder="Please prove you aren't a robot.">
          </div>
		  <button id="bt_contact" type="submit" class="btn btn-default">Submit</button>
		</form>	
	</div>
</div>


<br>
<br>
<br>
<br>
<br>
<br>
<br>

app/views/splash/directions.html.erb
<div class="container">
  <div class="image-container col-xs-12">
    <h1>Minus Zero Straton 2016 Lineup</h1>
    <p class="text-center"><%= image_tag("previous-lineup.png", alt: "Minus Zero", class: "img-responsive") %></p>   
    <h2>Minus Zero Straton 2016 Lineup</h2>
  </div>
  
</div>

app/views/splash/gallery.html.erb
<div class="container">
  <h1 class="page-title text-center">MINUS ZERO 2017 GALLERY</h1>
 
  <div id="gallery" style="display:none;">
    <% @thumbnail = "https://s3.amazonaws.com/minuszero2/thumbs1/" %>
    <% @thumb_num = 440 %>

    <% @big = "https://s3.amazonaws.com/minuszero2/" %>
    <% @big_num = 440 %>
    
    <!--total: 1060-->
    <% while @thumb_num != 490 && @big_num != 490 %>
        <%= image_tag(@thumbnail + @thumb_num.to_s + '.jpg', :class => 'margin-bottom', :alt => '', :'data-image' => image_url(@big + @big_num.to_s + '.jpg'), :'data-description' => 'MINUS ZERO 2017') %>
        <% @thumb_num += 1 %>
        <% @big_num += 1 %>
    <% end %>
  </div>
    
  <div style="margin-top: 30px;" id="ug_loadmore_wrapper" style="display:none;">
    <div class="ug-loadmore-button btn btn-default btn-block">LOAD MORE</div>  
    <div class="ug-loadmore-loader loading_gif" style="display:none;"><%= image_tag("loading.gif")%></div>
    <div class="ug-loadmore-error" style="display:none;">error...</div>
  </div>
  
</div>

app/views/splash/home.html.erb
<div class="hero">
  <div class="link-cover">
    <div class="video-overlay hidden-xs visible-sm visible-md visible-lg"><%= image_tag('mzf-logo.png')%></div>
    <%= video_tag("/minus-zero.mp4", controls: false, :autoplay => true, :loop => true, :muted => true)%>
  </div>
</div>
<div class="container-fluid" style="margin-top: -3px;">
  <div class="row">
    <div class="lineup col-xs-12" style="margin-top: -3px;">
      <div class="link-cover">
        <h2 class="page-title text-center" style="font-size: 4em;">2017 HEADLINERS</h2>
        <br>
        <!-- <h3 class="title text-center">Bassnectar + Griz + Zeds Dead</h3> -->
        <br>
        <div class="col-xs-12">
          <p class="text-center">
            <%= link_to "FULL LINE UP HERE!", lineup_path, :class => "btn btn-default" %>
          </p>
        </div>
      </div>
    </div>
    <div class="merch col-xs-12">
      <div class="link-cover">
        <div class="headers">
          <h2 class="page-title text-center" style="font-size: 4em;">NEW MINUS ZERO MERCH AVAILABLE</h2>
        <br>
        </div>
        <br>
        <p class="text-center"><%= link_to "SHOP MERCH", "http://merch.minuszerofestival.com/", :target => "_blank", :class => 'btn btn-default' %>
        </p>
      </div>
    </div>
    <div class="stratton col-xs-12">
      <div class="link-cover">
        <div class="headers">
          <h2 class="page-title text-center" style="font-size: 4em;">STRATTON RESORT</h2>
        <br>
        </div>
        <br>
        <p class="text-center"><%= link_to "LEARN MORE!", lodging_path, :class => 'btn btn-default' %>
        </p>
      </div>
    </div>
  </div>
</div><!-- container -->


   
<div class="modal fade" id="initialModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog vertical-align-center" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title text-center title" id="myModalLabel">STAY UP TO DATE WITH MINUS ZERO!</h4>
        <p class="text-center">Get first dibs on exclusive deals and offerings.</p>
      </div>
      <div class="modal-body">
        <form>
          <div class="form-group">
            <!-- <label for="recipient-name" class="control-label">Email:</label> -->
            <input type="email" class="form-control" id="emailModal" placeholder="Enter your email address here!">
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <!-- <button type="button" class="btn btn-default" data-dismiss="modal">Close</button> -->
        <button type="button" class="btn btn-default" id="btnModal" onclick="createModalEmail();">SUBSCRIBE NOW!</button>
      </div>
    </div>
  </div>
</div>    
    
<script>
    $( document ).ready(function() {
        setTimeout(function(){ loadPopUp(); }, 5000);
    });
</script>

app/views/splash/lodging.html.erb
<div class="lodging container">
	<h1 class="page-title text-center">Minus Zero Lodging</h1>
	<div class="stratton-lodging col-xs-12">
		<h2 class="title text-center">Official Lodging</h2>
		<div class="row">
			<div class="col-xs-12 col-md-3" style="padding-bottom: 15px;">
				<%= image_tag('stratton-logo.png') %>
			</div>
			<div class="col-xs-12 col-md-9">
				<div class="info">
					<p>
Stay at one of Stratton Mountain Resort’s awesome, diverse lodging options and be just a short walk away from the heart of the festival. Rooms, condos and townhouses are all going fast-  book today to secure your spot!</p>
				</div>
			</div>
		</div>
		<div class="hotel-images">
			<div class="row">
				<div class="col-xs-4 col-md-4">
					<%= image_tag('black-bear-lodge.jpg', :class => 'img-thumbnail') %>
				</div>
				<div class="col-xs-4 col-md-4">
					<%= image_tag('long-trail-lodge.jpg', :class => 'img-thumbnail') %>
				</div>
				<div class="col-xs-4 col-md-4">
					<%= image_tag('liftline-lodge.jpg', :class => 'img-thumbnail') %>
				</div>
			</div>
		</div>
		<p class="text-center"><%= link_to "MORE INFO", "https://www.stratton.com/plan-your-trip/lodging", :class => 'btn btn-default', :target => "_blank" %></p>
	</div>
	<div class="off-mountain col-xs-12">
		<h2 class="title text-center">Off Mountain Lodging</h2>
		<div class="row">
			<div class="col-xs-12 col-md-3" style="padding-bottom: 15px;">
				<%= image_tag('taconic-logo.png') %>
			</div>
			<div class="col-xs-12 col-md-9">
				<div class="info">
					<p>Kimpton Taconic is Southern Vermont’s newest upscale boutique hotel, located 18 miles from Stratton. Onsite restaurant and bar, The Copper Grouse, is a Manchester hot spot with farm to fork cuisine, craft cocktails, in a casual and contemporary setting. Dinner is served nightly, and Brunch is served on Saturday and Sunday.</p>
					<p>Within walking distance of Taconic guests can enjoy additional restaurants and bars, shopping, art galleries, and ample Vermont outdoor adventure.</p>
				</div>
			</div>
		</div>
		<div class="hotel-images">
			<div class="row">
				<div class="col-xs-4 col-md-4">
					<%= image_tag('taconic-hotel-1.jpg', :class => 'img-thumbnail') %>
				</div>
				<div class="col-xs-4 col-md-4">
					<%= image_tag('taconic-hotel-2.jpg', :class => 'img-thumbnail') %>
				</div>
				<div class="col-xs-4 col-md-4">
					<%= image_tag('taconic-hotel-3.jpg', :class => 'img-thumbnail') %>
				</div>
			</div>
		</div>
		<ul class="list-unstyled list-inline text-center">
			<li>
				<p class="text-center"><%= link_to "MORE INFO", "http://taconichotel.com", :class => 'btn btn-default', :target => "_blank" %></p>
			</li>
			<!-- <li>
				<p class="text-center"><%= link_to "BOOK A ROOM", "http://bit.ly/2MinusZeroFestivalTaconic", :class => 'btn btn-default', :target => "_blank" %></p>
			</li> -->
			
		</ul>
		
	</div>
</div>

app/views/splash/map.html.erb
<%= image_tag('stratmap.jpg') %>

app/views/splash/past-lineup.html.erb
<div class="col-xs-12 padding-top">
	<div class="container">
		<h1 class="lineup-header yellow text-center">2016 Lineup</h1>
		<%= image_tag('previous-lineup.png', :class => 'img-responsive')%>
		<br>
	</div>
	
</div>